logging:
  level:
    root: WARN
  file:
    path: ./logs
    name: ${logging.file.path}/application.log

spring:
  application:
    name: MindKeeperTgBot

  datasource:
    url: jdbc:postgresql://localhost:5432/mindkeeperdata
    username: postgres
    password: 586910
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  liquibase:
    enabled: true

bot:
  name: asdfsadtqertasdfasdBot
  token: 8979249563:AAEWPU8sOGKAriz2mR-hzFJqIpHjZ_q_ndI
  chatId: id_???????_????

server:
  port: 8081